### ISSUE TITLE
Redirection to GitHub when double-clicking

### ISSUE THREAD

**Issue by sk22** [leo/site#28]
As a person who uses the mouse cursor to select text while reading (for whatever reason), the redirection triggered by double-clicking annoys me (or, let's say, it limits my User Experience, or whatever).
I suggest removing that feature or moving the Easter egg elsewhere.

**Comment by leo** [comment]
I actually wrote it so it doesn't trigger when a text is being selected. At least that's how it works on macOS Safari, haven't tested Windows yet.

**Comment by sk22** [comment]
Yeah, it doesn't always redirect. But when I'm randomly messing around for a while, I find myself getting redirected to GitHub. This is something very minor anyway.

**Comment by leo** [comment]
If you're randomly messing around, that's exactly what should happen. The user should only remain on the site if he's trying to select some text... 😊
