### ISSUE TITLE
Process out of memory

### ISSUE THREAD

**Issue by austintoddj** [leo/site#30]
Hello! Great site by the way, really love it. I'm trying to get familiar with Next.js, so this is a nice little app to play around with as I explore it. Quick question regarding memory though:

I installed this on a Ubuntu 16.04 server and have the latest versions of Node and NPM installed. Running `npm run build` throws this error however:

<img width="916" alt="screen shot 2017-07-14 at 10 07 04 am" src="https://user-images.githubusercontent.com/8037011/28217901-719b84c8-687c-11e7-91f3-44aa931073ae.png">

Any insight or advice on a workaround?

**Comment by leo** [comment]
Yea... 😄 As this page is very huge, you'll need a lot of RAM to build it, that's due too the way how Next.js is built, I believe. Opening an issue for this... 😊
